release

diff --git a/.github/workflows/gha-event-callback.yaml b/.github/workflows/gha-event-callback.yaml
--- a/.github/workflows/gha-event-callback.yaml
+++ b/.github/workflows/gha-event-callback.yaml
@@ -9,8 +9,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
 
+      - name: Check Event Type - ${{ github.event.client_payload.state }}
+        id: check_event_type
+        if: |
+          !contains(fromJson('["pending", "success", "failure"]'), github.event.client_payload.state)
+        run: |
+          echo "Invalid event typed"
+          exit 1
+
       - name: Callback - ${{ github.event.client_payload.state }}
-        if: contains(fromJson('["pending", "success", "failure"]'), github.event.client_payload.state)
         run: |
           curl --request POST \
           --url ${{ github.event.client_payload.statuses_href }} \
@@ -26,7 +33,10 @@ jobs:
           
       
       - name: Intenal error ❌
-        if: ${{ failure() && github.event.client_payload.state != 'failure'}}
+        if: |
+          failure() && 
+          github.event.client_payload.state != 'failure' &&
+          steps.check_event_type.outcome == 'success'
         run: |
           curl --request POST \
           --url ${{ github.event.client_payload.statuses_href }} \
